PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE users(name TEXT);
CREATE TABLE card(question text, answer text);
INSERT INTO "card" VALUES('Afghanistan','Kabul');
INSERT INTO "card" VALUES('Albania','Tirane');
INSERT INTO "card" VALUES('Algeria','Algiers');
INSERT INTO "card" VALUES('Andorra','Andorra la Vella');
INSERT INTO "card" VALUES('Angola','Luanda');
INSERT INTO "card" VALUES('Antigua and Barbuda','Saint John''s');
INSERT INTO "card" VALUES('Argentina','Buenos Aires');
INSERT INTO "card" VALUES('Armenia','Yerevan');
INSERT INTO "card" VALUES('Australia','Canberra');
INSERT INTO "card" VALUES('Austria','Vienna');
INSERT INTO "card" VALUES('Azerbaijan','Baku');
INSERT INTO "card" VALUES('The Bahamas','Nassau');
INSERT INTO "card" VALUES('Bahrain','Manama');
INSERT INTO "card" VALUES('Bangladesh','Dhaka');
INSERT INTO "card" VALUES('Barbados','Bridgetown');
INSERT INTO "card" VALUES('Belarus','Minsk');
INSERT INTO "card" VALUES('Belgium','Brussels');
INSERT INTO "card" VALUES('Belize','Belmopan');
INSERT INTO "card" VALUES('Benin','Porto-Novo');
INSERT INTO "card" VALUES('Bhutan','Thimphu');
INSERT INTO "card" VALUES('Bolivia','Sucre');
INSERT INTO "card" VALUES('Bosnia and Herzegovina','Sarajevo');
INSERT INTO "card" VALUES('Botswana','Gaborone');
INSERT INTO "card" VALUES('Brazil','Brasilia');
INSERT INTO "card" VALUES('Brunei','Bandar Seri Begawan');
INSERT INTO "card" VALUES('Bulgaria','Sofiya');
INSERT INTO "card" VALUES('Burkina Faso','Ouagadougou');
INSERT INTO "card" VALUES('Burundi','Bujumbura');
INSERT INTO "card" VALUES('Cambodia','Phnom Penh');
INSERT INTO "card" VALUES('Cameroon','Yaounde');
INSERT INTO "card" VALUES('Canada','Ottawa');
INSERT INTO "card" VALUES('Cape Verde','Praia');
INSERT INTO "card" VALUES('Central African Republic','Bangui');
INSERT INTO "card" VALUES('Chad','N''Djamena');
INSERT INTO "card" VALUES('Chile','Santiago');
INSERT INTO "card" VALUES('China','Beijing');
INSERT INTO "card" VALUES('Colombia','Bogota');
INSERT INTO "card" VALUES('Comoros','Moroni');
INSERT INTO "card" VALUES('Republic of the Congo','Brazzaville');
INSERT INTO "card" VALUES('Democratic Republic of the Congo','Kinshasa');
INSERT INTO "card" VALUES('Costa Rica','San Jose');
INSERT INTO "card" VALUES('Cote d''Ivoire','Yamoussoukro');
INSERT INTO "card" VALUES('Croatia','Zagreb');
INSERT INTO "card" VALUES('Cuba','Havana');
INSERT INTO "card" VALUES('Cyprus','Nicosia');
INSERT INTO "card" VALUES('Czech Republic','Prague');
INSERT INTO "card" VALUES('Denmark','Copenhagen');
INSERT INTO "card" VALUES('Djibouti','Djibouti');
INSERT INTO "card" VALUES('Dominica','Roseau');
INSERT INTO "card" VALUES('Dominican Republic','Santo Domingo');
INSERT INTO "card" VALUES('East Timor','Dili');
INSERT INTO "card" VALUES('Ecuador','Quito');
INSERT INTO "card" VALUES('Egypt','Cairo');
INSERT INTO "card" VALUES('El Salvador','San Salvador');
INSERT INTO "card" VALUES('Equatorial Guinea','Malabo');
INSERT INTO "card" VALUES('Eritrea','Asmara');
INSERT INTO "card" VALUES('Estonia','Tallinn');
INSERT INTO "card" VALUES('Ethiopia','Addis Ababa');
INSERT INTO "card" VALUES('Fiji','Suva');
INSERT INTO "card" VALUES('Finland','Helsinki');
INSERT INTO "card" VALUES('France','Paris');
INSERT INTO "card" VALUES('Gabon','Libreville');
INSERT INTO "card" VALUES('The Gambia','Banjul');
INSERT INTO "card" VALUES('Georgia','Tbilisi');
INSERT INTO "card" VALUES('Germany','Berlin');
INSERT INTO "card" VALUES('Ghana','Accra');
INSERT INTO "card" VALUES('Greece','Athens');
INSERT INTO "card" VALUES('Grenada','Saint George''s');
INSERT INTO "card" VALUES('Guatemala','Guatemala City');
INSERT INTO "card" VALUES('Guinea','Conakry');
INSERT INTO "card" VALUES('Guinea-Bissau','Bissau');
INSERT INTO "card" VALUES('Guyana','Georgetown');
INSERT INTO "card" VALUES('Haiti','Port-au-Prince');
INSERT INTO "card" VALUES('Holy See','Vatican City');
INSERT INTO "card" VALUES('Honduras','Tegucigalpa');
INSERT INTO "card" VALUES('Hungary','Budapest');
INSERT INTO "card" VALUES('Iceland','Reykjavik');
INSERT INTO "card" VALUES('India','New Delhi');
INSERT INTO "card" VALUES('Indonesia','Jakarta');
INSERT INTO "card" VALUES('Iran','Tehran');
INSERT INTO "card" VALUES('Iraq','Baghdad');
INSERT INTO "card" VALUES('Ireland','Dublin');
INSERT INTO "card" VALUES('Israel','Jerusalem');
INSERT INTO "card" VALUES('Italy','Rome');
INSERT INTO "card" VALUES('Jamaica','Kingston');
INSERT INTO "card" VALUES('Japan','Tokyo');
INSERT INTO "card" VALUES('Jordan','Amman');
INSERT INTO "card" VALUES('Kazakhstan','Astana');
INSERT INTO "card" VALUES('Kenya','Nairobi');
INSERT INTO "card" VALUES('Kiribati','Tarawa');
INSERT INTO "card" VALUES('North Korea','Pyongyang');
INSERT INTO "card" VALUES('South Korea','Seoul');
INSERT INTO "card" VALUES('Kuwait','Kuwait City');
INSERT INTO "card" VALUES('Kyrgyzstan','Bishkek');
INSERT INTO "card" VALUES('Laos','Vientiane');
INSERT INTO "card" VALUES('Latvia','Riga');
INSERT INTO "card" VALUES('Lebanon','Beirut');
INSERT INTO "card" VALUES('Lesotho','Maseru');
INSERT INTO "card" VALUES('Liberia','Monrovia');
INSERT INTO "card" VALUES('Libya','Tripoli');
INSERT INTO "card" VALUES('Liechtenstein','Vaduz');
INSERT INTO "card" VALUES('Lithuania','Vilnius');
INSERT INTO "card" VALUES('Luxembourg','Luxembourg');
INSERT INTO "card" VALUES('Macedonia','Skopje');
INSERT INTO "card" VALUES('Madagascar','Antananarivo');
INSERT INTO "card" VALUES('Malawi','Lilongwe');
INSERT INTO "card" VALUES('Malaysia','Kuala Lumpur');
INSERT INTO "card" VALUES('Maldives','Male');
INSERT INTO "card" VALUES('Mali','Bamako');
INSERT INTO "card" VALUES('Malta','Valletta');
INSERT INTO "card" VALUES('Marshall Islands','Majuro');
INSERT INTO "card" VALUES('Mauritania','Nouakchott');
INSERT INTO "card" VALUES('Mauritius','Port Louis');
INSERT INTO "card" VALUES('Mexico','Mexico');
INSERT INTO "card" VALUES('Federated States of Micronesia','Palikir');
INSERT INTO "card" VALUES('Moldova','Chisinau');
INSERT INTO "card" VALUES('Monaco','Monaco');
INSERT INTO "card" VALUES('Mongolia','Ulaanbaatar');
INSERT INTO "card" VALUES('Morocco','Rabat');
INSERT INTO "card" VALUES('Mozambique','Maputo');
INSERT INTO "card" VALUES('Myanmar','Rangoon');
INSERT INTO "card" VALUES('Namibia','Windhoek');
INSERT INTO "card" VALUES('Nauru','Yaren');
INSERT INTO "card" VALUES('Nepal','Kathmandu');
INSERT INTO "card" VALUES('Netherlands','Amsterdam');
INSERT INTO "card" VALUES('New Zealand','Wellington');
INSERT INTO "card" VALUES('Nicaragua','Managua');
INSERT INTO "card" VALUES('Niger','Niamey');
INSERT INTO "card" VALUES('Nigeria','Abuja');
INSERT INTO "card" VALUES('Norway','Oslo');
INSERT INTO "card" VALUES('Oman','Muscat');
INSERT INTO "card" VALUES('Pakistan','Islamabad');
INSERT INTO "card" VALUES('Palau','Koror');
INSERT INTO "card" VALUES('Panama','Panama');
INSERT INTO "card" VALUES('Papua New Guinea','Port Moresby');
INSERT INTO "card" VALUES('Paraguay','Asuncion');
INSERT INTO "card" VALUES('Peru','Lima');
INSERT INTO "card" VALUES('Philippines','Manila');
INSERT INTO "card" VALUES('Poland','Warsaw');
INSERT INTO "card" VALUES('Portugal','Lisbon');
INSERT INTO "card" VALUES('Qatar','Doha');
INSERT INTO "card" VALUES('Romania','Bucharest');
INSERT INTO "card" VALUES('Russia','Moscow');
INSERT INTO "card" VALUES('Rwanda','Kigali');
INSERT INTO "card" VALUES('Saint Kitts and Nevis','Basseterre');
INSERT INTO "card" VALUES('Saint Lucia','Castries');
INSERT INTO "card" VALUES('Saint Vincent and the Grenadines','Kingstown');
INSERT INTO "card" VALUES('Samoa','Apia');
INSERT INTO "card" VALUES('San Marino','San Marino');
INSERT INTO "card" VALUES('Sao Tome and Principe','Sao Tome');
INSERT INTO "card" VALUES('Saudi Arabia','Riyadh');
INSERT INTO "card" VALUES('Senegal','Dakar');
INSERT INTO "card" VALUES('Serbia and Montenegro','Belgrade');
INSERT INTO "card" VALUES('Seychelles','Victoria');
INSERT INTO "card" VALUES('Sierra Leone','Freetown');
INSERT INTO "card" VALUES('Singapore','Singapore');
INSERT INTO "card" VALUES('Slovakia','Bratislava');
INSERT INTO "card" VALUES('Slovenia','Ljubljana');
INSERT INTO "card" VALUES('Solomon Islands','Honiara');
INSERT INTO "card" VALUES('Somalia','Mogadishu');
INSERT INTO "card" VALUES('South Africa','Pretoria');
INSERT INTO "card" VALUES('Spain','Madrid');
INSERT INTO "card" VALUES('Sri Lanka','Colombo');
INSERT INTO "card" VALUES('Sudan','Khartoum');
INSERT INTO "card" VALUES('Suriname','Paramaribo');
INSERT INTO "card" VALUES('Swaziland','Mbabane');
INSERT INTO "card" VALUES('Sweden','Stockholm');
INSERT INTO "card" VALUES('Switzerland','Zurich');
INSERT INTO "card" VALUES('Syria','Damascus');
INSERT INTO "card" VALUES('Taiwan','Taipei');
INSERT INTO "card" VALUES('Tajikistan','Dushanbe');
INSERT INTO "card" VALUES('Tanzania','Dar es Salaam');
INSERT INTO "card" VALUES('Thailand','Bangkok');
INSERT INTO "card" VALUES('Togo','Lome');
INSERT INTO "card" VALUES('Tonga','Nukualofa');
INSERT INTO "card" VALUES('Trinidad and Tobago','Port-of-Spain');
INSERT INTO "card" VALUES('Tunisia','Tunis');
INSERT INTO "card" VALUES('Turkey','Ankara');
INSERT INTO "card" VALUES('Turkmenistan','Ashgabat');
INSERT INTO "card" VALUES('Tuvalu','Fongafale');
INSERT INTO "card" VALUES('Uganda','Kampala');
INSERT INTO "card" VALUES('Ukraine','Kiev');
INSERT INTO "card" VALUES('United Arab Emirates','Abu Dhabi');
INSERT INTO "card" VALUES('United Kingdom','London');
INSERT INTO "card" VALUES('United States of America','Washington D.C.');
INSERT INTO "card" VALUES('Uruguay','Montevideo');
INSERT INTO "card" VALUES('Uzbekistan','Tashkent');
INSERT INTO "card" VALUES('Vanuatu','Port Vila');
INSERT INTO "card" VALUES('Venezuela','Caracas');
INSERT INTO "card" VALUES('Vietnam','Hanoi');
INSERT INTO "card" VALUES('Yemen','Sanaa');
INSERT INTO "card" VALUES('Zambia','Lusaka');
INSERT INTO "card" VALUES('Zimbabwe','Harare');
COMMIT;
